name: Publish new frontend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.3
    - name: Run npm build
      run: |
        cd frontend
        npm install
        npm run build
    - name: Push to azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.1
        inlineScript: |
          az storage blob sync -s ./build/ -c '$web' --connection-string "${{secrets.STORAGE_KEY1}}"
